### ISSUE TITLE
[Admin] Activity backend page

### ISSUE THREAD

**Issue by abigail830** [abigail830/blindbox#4]
--------------------------------------
Admin backend page for Activity CRUD
Activity info contained: 
- 首页图（1个，尺寸要求？）
- 标题（字长？）
- 内容图（n个，尺寸要求？）
- CreateTime/LastUpdateTime
- ActivityStartTime/ActivityEndTime
- ifShowInAd?

## Task
- [x] create db table for activity
- [x] As an admin,  I can see the defined Activity 
- [x] As an admin, when click add button, it jump to Activity create page, and Activity could be add successfully.
- [x] As an admin, when click edit button, it jump to Activity edit page, when Activity record could be update
- [x] As an admin, when click delete, it would have a popup to double confirm, if yes, then Activity will be remove.
- [x] validation of date/image
- [x] rich editor contain both text and image

High level estimation: 2-3MD

**Comment by abigail830** [comment]
- no validation for the pic size and format yet.
- url for wx access: /wx/activities/front-page (showing those activities marked to show in front-page slider)

**Comment by abigail830** [comment]
quill的值在innerHtml里面，如果使用thymeleaf binding的话， th:utext可以显示值，但是th:name post不了
